
local function CreateWindow(Table)
    local WindowInfo = Table["Info"]
    if (WindowInfo["ClassName"] = "Window") then
        local ScreenGui = Instance.new("ScreenGui")
        local Main = Instance.new("Frame")
        local UICorner = Instance.new("UICorner")
        local Side = Instance.new("Frame")
        local UICorner_2 = Instance.new("UICorner")
        local Title = Instance.new("TextLabel")
        local Holder = Instance.new("ScrollingFrame")
        local Tab = Instance.new("TextButton")
        local UIListLayout = Instance.new("UIListLayout")
        local Tab_2 = Instance.new("TextButton")
        local Seperator = Instance.new("Frame")
        local UICorner_3 = Instance.new("UICorner")
        local DiscordButton = Instance.new("ImageButton")
        local UIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
        local DiscordLabel = Instance.new("TextButton")
        local Top = Instance.new("Frame")
        local Close = Instance.new("ImageButton")
        local UICorner_4 = Instance.new("UICorner")
        local Page = Instance.new("ScrollingFrame")
        local Button = Instance.new("Frame")
        local UICorner_5 = Instance.new("UICorner")
        local ButtonButton = Instance.new("TextButton")
        local ButtonLabel = Instance.new("TextLabel")
        local UIListLayout_2 = Instance.new("UIListLayout")
        local Toggle = Instance.new("Frame")
        local UICorner_6 = Instance.new("UICorner")
        local ToggleLabel = Instance.new("TextLabel")
        local ToggleButtonFrame = Instance.new("Frame")
        local UICorner_7 = Instance.new("UICorner")
        local ToggleButton = Instance.new("ImageButton")
        local Label = Instance.new("Frame")
        local UICorner_8 = Instance.new("UICorner")
        local Label_2 = Instance.new("TextLabel")
        local Seperator_2 = Instance.new("Frame")
        local UICorner_9 = Instance.new("UICorner")
        local Slider = Instance.new("Frame")
        local UICorner_10 = Instance.new("UICorner")
        local SliderLabel = Instance.new("TextLabel")
        local Bar = Instance.new("Frame")
        local UICorner_11 = Instance.new("UICorner")
        local Val = Instance.new("TextLabel")
        local Fill = Instance.new("Frame")
        local UICorner_12 = Instance.new("UICorner")
        local Logo = Instance.new("ImageLabel")

        local WindowChildren = Table["Children"]
    else
        warn("No Window to be created.")
    end
end